#! /bin/sh
                                                         
#     @@@@@@@    @@@@@@   @@@@@@@   @@@  @@@  @@@  @@@@@@@@@@   
#     @@@@@@@@  @@@@@@@   @@@@@@@@  @@@  @@@  @@@  @@@@@@@@@@@  
#     @@!  @@@  !@@       @@!  @@@  @@!  @@!  @@!  @@! @@! @@!  
#     !@   @!@  !@!       !@!  @!@  !@!  !@!  !@!  !@! !@! !@!  
#     @!@!@!@   !!@@!!    @!@@!@!   @!!  !!@  @!@  @!! !!@ @!@  
#     !!!@!!!!   !!@!!!   !!@!!!    !@!  !!!  !@!  !@!   ! !@!  
#     !!:  !!!       !:!  !!:       !!:  !!:  !!:  !!:     !!:  
#     :!:  !:!      !:!   :!:       :!:  :!:  :!:  :!:     :!:  
#      :: ::::  :::: ::    ::        :::: :: :::   :::     ::   
#     :: : ::   :: : :     :          :: :  : :     :      :    
                                                          
#____________________ARRANQUE DEL SISETMA_____________________

export PATH="${PATH}:$HOME/.config/lemonbar"
export PATH="${PATH}:$HOME/.config/bspwm/scripts"
sxhkd &
picom &
nitrogen --restore &
pgrep -x sxhkd > /dev/null
pkill -9 panel
panel &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(gnome-keyring-daemon -s -- components=pkcs11,secrets,ssh,gpg) &
curl -sf "wttr.in/florencio+varela?lang=es" > "$HOME/.config/weatherreport" &
unclutter &
xsetroot -cursor_name left_ptr &

#_______________CONFIGURACION DE 1 Y 2 MONITORES_____________

bspc monitor -d  一  二  三  四  五  六  七  八  九 
#bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 6 7 8 9
#bspc monitor HDMI3 -d 1 2 3 4 5

#______________________BORDES Y COLORES/CONF BSPWM_______________________

bspc config border_width 	2
bspc config window_gap 		15
bspc config top_padding		20
bspc config focused_border_color "#03B4CB"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#_____________REGLAS DE COMPORTAMIENTO DE VENTANAS/AREAS DE TRABAJO____________

bspc rule -a mpv state=floating
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a Zathura state=tiled
