#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/lemonbar/panel &
curl -sf "wttr.in/florencio+varela?lang=es" > "$HOME/.config/weatherreport" &
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(gnome-keyring-daemon -s -- components=pkcs11,secrets,ssh,gpg) &
dunst &
picom &
unclutter &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d 一  二  三  四  五  六  七  八  九

bspc config border_width 	2
bspc config window_gap 		15
bspc config top_padding		20

bspc config focused_border_color "#03B4CB"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc rule -a Zathura state=tiled

