#! /bin/sh

#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░


#____________________ARRANQUE DEL SISTEMA_____________________

export SUDO_ASKPASS="$HOME/.local/bin/scripts/pass"
export PATH="${PATH}:$HOME/.local/bin/scripts"
export PATH="$PATH:$(du "$HOME/.local/bin/modulos/" | cut -f2 | paste -sd ':' -)"
export EDITOR=nvim
pkill -9 polybar &
picom &
nitrogen --restore &
sxhkd &
pgrep -x sxhkd > /dev/null
polybar bar1 &
polybar bar2 &
dunst &
temas &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(gnome-keyring-daemon -s -- components=pkcs11,secrets,ssh,gpg) &
unclutter &
xsetroot -cursor_name left_ptr &
wmname 'LG3D'
#_______________CONFIGURACION DE 1 Y 2 MONITORES________________________

bspc monitor -d  一 二 三 四 五 六 七 八 九 零
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 0000 0001 0010 0011 0100 0101 0111 1000 1100
#bspc monitor -d 1 2 3 4 5 6 7 8 9
#xrandr --output VGA-2-1 --mode 1440x900 --right-of HDMI-A-2 --rotate normal
#xrandr -s 1600x900
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#bspc monitor LVDS1 -d 1 2 3 4 5
#bspc monitor VGA1 -d 6 7 8 9 

#______________________BORDES Y COLORES/CONF BSPWM_______________________

bspc config border_width 	2
bspc config window_gap 		15
bspc config top_padding		30
bspc config bottom_padding	30
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config automatic_scheme longest_side
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config focused_frame_opacity 0.05
#bspc config normal_frame_opacity 1.0
#___________________ FullCOLOR Theme _______________________
bspc config urgent_border_color "#dd2727"
bspc config focused_border_color "#03B4CB"
bspc config presel_feedback_color "#FF492B"
#___________________ Black Theme ___________________________
#bspc config focused_border_color "#dddddd"
#bspc config presel_feedback_color "#FF492B"
#___________________ Dracula Theme __________________________
#bspc config focused_border_color "#FF79C6"
#bspc config presel_feedback_color "#8BE9FD"

#_____________REGLAS DE COMPORTAMIENTO DE VENTANAS/AREAS DE TRABAJO____________

bspc rule -a Blueberry.py state=floating center=true
bspc rule -a Zathura state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Nitrogen state=floating rectangle=800x500+0+0 center=on
