#!/bin/bash

reload_bspwm="bspc wm -r;dunstify -i $HOME/.config/dunst/iconpng/arch.png BSPWMRC RECARGADO"
reload_sxhkd="pkill -USR1 -x sxhkd;dunstify -i $HOME/.config/dunst/iconpng/arch.png SXHKDRC RECARGADO"
reb="reboot"
shut="poweroff"
logout="killall panel;bspc quit"

cmds="\
 Bloquear                        	slock
 Cerrar Sesion                   	${logout}
 Recargar BSPwm                  	${reload_bspwm}
 Recargar Sxhkd                  	${reload_sxhkd}
 Reinciar PC                     	${reb}
 Apagar PC                       	${shut}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

action=$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2)

IFS=';' read -ra com <<< "$action"

for i in "${com[@]}"
do
$i
done
