#! /bin/sh

# LEMONBAR BY MXHECTORVEGA - PRINCIPIADA CON ARCHIVOS EXAMPLES

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=21
PANEL_WM_NAME=bspwm_panel
PANEL_FONT_FAMILY="Source Han Sans JP:Bold:size=10"
ICON_FONT="Font Awesome:size=10"

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0'B TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

xtitle -sf xtitle -sf 'T%s\n' -t50 > "$PANEL_FIFO" &
clock -sf 'S%a, %d %b %H:%M' > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &
temp -sf'C%.1f' -n0 > "$PANEL_FIFO" &
battery -sf'B%i' -n0 > "$PANEL_FIFO" &

. $HOME/.config/lemonbar/panel_colors

. $HOME/.config/lemonbar/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -u 2 -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &
wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
